/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u         /*!<@brief Input Buffer Enable: Enables */
#define PORT2_PCR4_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR5_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT1_7 (number 1), RED_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RED_LED_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RED_LED_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_RED_LED_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RED_LED_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RED_LED_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RED_LED_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_4 (number 62), GREEN_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GREEN_LED_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GREEN_LED_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_GREEN_LED_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GREEN_LED_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GREEN_LED_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GREEN_LED_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT1_6 (number 64), YELLOW_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_YELLOW_LED_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_YELLOW_LED_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_YELLOW_LED_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_YELLOW_LED_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_YELLOW_LED_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_YELLOW_LED_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT1_5 (number 63), IN_4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IN_4_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IN_4_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IN_4_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IN_4_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IN_4_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IN_4_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_4 (number 18), IN_3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IN_3_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IN_3_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IN_3_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IN_3_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IN_3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IN_3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_5 (number 19), IN_2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IN_2_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IN_2_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IN_2_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IN_2_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IN_2_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IN_2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_12 (number 38), IN_1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IN_1_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IN_1_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IN_1_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IN_1_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IN_1_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IN_1_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT3_13 (number 37), BUZZER
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BUZZER_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BUZZER_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BUZZER_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT3_15 (number 35), HCSR04_ECHO
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HCSR04_ECHO_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HCSR04_ECHO_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_HCSR04_ECHO_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HCSR04_ECHO_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HCSR04_ECHO_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HCSR04_ECHO_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_14 (number 36), HCSR04_TRIG
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HCSR04_TRIG_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HCSR04_TRIG_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_HCSR04_TRIG_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HCSR04_TRIG_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HCSR04_TRIG_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HCSR04_TRIG_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
